local:
  type: "postgres"
  host: "localhost"
  port: 5432
  username: "server"
  password: "server"
  database: "serverdb"
  entities: ["./src/modules/**/infra/typeorm/entities/*.ts"]
  migrations: ["./src/shared/infra/typeorm/migrations/*.ts"]
  cli: {
    migrationsDir: "./src/shared/infra/typeorm/migrations"
  }
